### ISSUE TITLE
Need some words to explain why FiberScheduler is userland

### ISSUE THREAD

**Issue by Danack** [trowski/fiber-rfc#2]
currently the RFC doesn't explain why FiberScheduler is only an interface.

Need to say someone about allowing implementation details to be worked out, and that it's expected each framework to write their own implementation, but they will probably be compatible, i.e. that libraries that take advantage of this RFC, would be usable in any of those frameworks that talk 'fibres'.

**Comment by trowski** [comment]
In an ideal world we could just put an implementation using libuv (or other I guess, but libuv seems the most obvious choice) in core immediately, but this seems like a huge first step, so that's why I went with this approach.

Multiple schedulers can work together, though only one can be executing at a single time due to the single-threaded nature. In a php-fpm application that's probably fine, but a truly async app would want to use a single scheduler (as it always has).

**Comment by trowski** [comment]
Added in FAQs under "Why not add an event loop and async/await API to core?"
